# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.destroy_all
Post.destroy_all

categories = Category.create([
  { name: 'News'}, { name: 'Sport' }, { name: 'Weather' }
])

posts = Post.create([
  { title: 'NW, now where?', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'News').first },
    { title: 'I\'ve had a few', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Sport').first },
    { title: 'Hazy Jane', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'Chime of the city clock', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'News').first },
    { title: 'Northern Sky', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'Milk and Honey', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'Come into the garden', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'News').first },
    { title: 'Way too blue', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'Strange Meeting', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'Tally-ho, pip-pip, don\'t bother', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Sport').first },
    { title: 'The Chain', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
    { title: 'You Make Loving Fun', content: "High Life ugh hashtag, Carles VHS tofu craft beer banjo fingerstache sartorial Bushwick cornhole. Vinyl Godard authentic selvage forage lo-fi. Tote bag church-key meggings kitsch disrupt you probably haven't heard of them, Vice pour-over direct trade cornhole literally selfies VHS. Hashtag Tonx put a bird on it fap, helvetica semiotics craft beer Odd Future. Organic flannel Vice, selvage seitan 90's Godard intelligentsia cornhole. Schlitz dreamcatcher try-hard put a bird on it keffiyeh, mlkshk seitan High Life raw denim Cosby sweater helvetica Neutra selfies street art. Whatever before they sold out Carles tousled church-key.", category: Category.where(name: 'Weather').first },
])
